# Generated by Django 5.1.1 on 2024-10-03 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about_company/', verbose_name='Логотип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_company/', verbose_name='Фото')),
                ('greeting', models.TextField(verbose_name='Приветствие для клиентов')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_days', models.CharField(help_text='5/2, 2/2, 3/3 и пр.', max_length=255, verbose_name='Рабочие дни')),
                ('work_time', models.CharField(max_length=255, verbose_name='Рабочие часы')),
                ('phone', models.CharField(default='+7', help_text='Введите телефон в формате +79001112233', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +79001112233', regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя клиента', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(help_text='укажите email', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='+7', help_text='Введите телефон в формате +79001112233', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +79001112233', regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персона',
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit_bot', models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение бота')),
                ('last_visit_web', models.DateTimeField(blank=True, null=True, verbose_name='Последнее посещение web')),
                ('is_blocked', models.BooleanField(blank=True, null=True, verbose_name='Бот заблокирован')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.client', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Активность клиента',
                'verbose_name_plural': 'Активность клиентов',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Оценка')),
                ('photo', models.ImageField(upload_to='masters/', verbose_name='Фото мастера')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.client', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Рабочий день')),
                ('start_time', models.TimeField(default='10:00:00', verbose_name='Начало работы')),
                ('end_time', models.TimeField(default='21:00:00', verbose_name='Конец работы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'График работы мастера',
                'verbose_name_plural': 'Графики работы мастеров',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('duration', models.IntegerField(verbose_name='Длительность выполнения (минут)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Картинка услуги')),
                ('price', models.IntegerField(verbose_name='Цена(рублей)')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='base_process.categories', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, to='base_process.service', verbose_name='Услуги'),
        ),
        migrations.CreateModel(
            name='VisitJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания записи')),
                ('visit_date', models.DateTimeField(verbose_name='Дата посещения')),
                ('confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждение')),
                ('cancel', models.BooleanField(default=False, verbose_name='Услуга отменена')),
                ('finish', models.BooleanField(default=False, verbose_name='Услуга оказана')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('math_action', models.CharField(choices=[('plus', 'Прибавление'), ('minus', 'Вычитание')], default='plus', max_length=255, verbose_name='Действие')),
                ('math_value', models.IntegerField(blank=True, help_text='Значение должно быть кратным 15', null=True, verbose_name='Значение')),
                ('visit_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.client', verbose_name='Клиент')),
                ('visit_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.master', verbose_name='Мастер')),
                ('visit_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_process.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Журнал посещений',
                'verbose_name_plural': 'Журнал посещений',
            },
        ),
    ]
