# Generated by Django 5.0 on 2024-10-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_funcs', '0004_promotion_discount'),
        ('base_process', '0002_remove_service_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitjournal',
            name='promotion_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_funcs.promotion', verbose_name='Акция'),
        ),
    ]
