# Generated by Django 5.0 on 2024-10-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_process', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
