# Generated by Django 5.0 on 2024-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_process', '0006_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Картинка услуги'),
        ),
    ]
