# Generated by Django 5.0 on 2024-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_funcs', '0005_alter_abonementsjournal_purchased_abonement'),
        ('base_process', '0007_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitjournal',
            name='promotion_discount',
            field=models.ManyToManyField(blank=True, to='add_funcs.promotion', verbose_name='Акция'),
        ),
    ]
