# Generated by Django 5.0 on 2024-10-04 07:56

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_process', '0009_alter_visitjournal_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/', validators=[utils.models.validate_image_or_svg], verbose_name='Картинка услуги'),
        ),
    ]
