# Generated by Django 5.0 on 2024-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_process', '0011_alter_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_active_role',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='master',
            name='is_active_role',
            field=models.BooleanField(default=True),
        ),
    ]
