# Generated by Django 5.0 on 2024-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_process', '0012_admin_is_active_role_master_is_active_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_active_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active_role',
            field=models.BooleanField(default=False),
        ),
    ]
