# Generated by Django 5.0 on 2024-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_funcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_toggle', models.BooleanField(default=True, help_text='Автоматически подключать программу лояльности клиентам при наличии акций, абонементов и сертификатов', verbose_name='Автоматический режим')),
                ('toggle', models.BooleanField(default=True, help_text='Включить/выключить программу лояльности для отображения у клиентов', verbose_name='Включена')),
            ],
            options={
                'verbose_name': 'Программа лояльности (вкл/выкл)',
                'verbose_name_plural': 'Программа лояльности (вкл/выкл)',
            },
        ),
        migrations.AlterModelOptions(
            name='chatwithadmin',
            options={'verbose_name': 'Чат с админом (вкл/выкл)', 'verbose_name_plural': 'Чат с админом (вкл/выкл)'},
        ),
    ]
