# Generated by Django 5.0 on 2024-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_funcs', '0002_loyaltyprogram_alter_chatwithadmin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='toggle',
            field=models.BooleanField(default=False, help_text='Включить/выключить программу лояльности для отображения у клиентов', verbose_name='Включена'),
        ),
    ]
