# Generated by Django 5.0 on 2024-10-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_funcs', '0004_promotion_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonementsjournal',
            name='purchased_abonement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_funcs.abonement', verbose_name='Абонемент'),
        ),
    ]
